import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Theaters
  const theaters = [
    { id: 'kupala', name: 'Национальный академический театр имени Янки Купалы', shortName: 'Купаловский' },
    { id: 'gorky', name: 'Национальный академический драматический театр имени М. Горького', shortName: 'Горьковский' },
    { id: 'youth', name: 'Белорусский государственный молодёжный театр', shortName: 'Молодёжный' },
    { id: 'rtbd', name: 'Республиканский театр белорусской драматургии', shortName: 'РТБД' },
    { id: 'oblast', name: 'Минский областной драматический театр', shortName: 'Областной' },
    { id: 'kino', name: 'Театр-студия киноактёра', shortName: 'Киноактёр' },
  ];

  for (const t of theaters) {
    await prisma.theater.upsert({ where: { id: t.id }, update: t, create: t });
  }

  const performances = [
    {
      id: '1',
      theaterId: 'kupala',
      title: 'Павлинка',
      genre: 'Комедия',
      duration: '2ч 30мин',
      director: 'Николай Пинигин',
      synopsis: 'Классическая белорусская комедия Янки Купалы о молодой девушке Павлинке, которая борется за своё право на счастье и любовь вопреки воле отца. Яркий, жизнерадостный спектакль, пропитанный белорусским колоритом и народным юмором.',
      imageUrl: '/images/performance-1.jpg',
      heroImageUrl: '/images/performance-1-hero.png',
      rating: 4.7,
      reviewCount: 124,
      premiere: '1944',
      emotionProfile: [
        { emotion: 'joy', score: 85 },
        { emotion: 'melancholy', score: 15 },
        { emotion: 'tension', score: 25 },
        { emotion: 'passion', score: 45 },
        { emotion: 'wonder', score: 70 },
        { emotion: 'sadness', score: 10 },
      ],
      targetAudience: ['Семейный просмотр', 'Любители классики', 'Первый поход в театр', 'Для иностранных гостей'],
      cast: ['Зоя Белохвостик', 'Геннадий Овсянников', 'Мария Захаревич'],
      reviews: [
        { id: 'r1', author: 'Мария К.', date: '2025-12-15', rating: 5, text: 'Потрясающий спектакль! Актёры играют великолепно, а атмосфера просто волшебная. Рекомендую всем!', emotions: [{ emotion: 'joy', score: 90 }, { emotion: 'wonder', score: 80 }] },
        { id: 'r2', author: 'Андрей П.', date: '2025-11-20', rating: 4, text: 'Классическая постановка, но актёрская игра на высоте. Отличный вечер в театре.', emotions: [{ emotion: 'joy', score: 75 }, { emotion: 'wonder', score: 60 }] },
      ],
    },
    {
      id: '2',
      theaterId: 'kupala',
      title: 'Пинская шляхта',
      genre: 'Комедия',
      duration: '1ч 50мин',
      director: 'Валерий Анисенко',
      synopsis: 'Острая сатирическая комедия Винцента Дунина-Марцинкевича. Спектакль высмеивает мелкопоместное дворянство, их амбиции и нравы. Яркие характеры и остроумные диалоги делают эту постановку одной из самых популярных.',
      imageUrl: '/images/performance-2.jpg',
      heroImageUrl: '/images/performance-2-hero.png',
      rating: 4.5,
      reviewCount: 89,
      premiere: '1956',
      emotionProfile: [
        { emotion: 'joy', score: 78 },
        { emotion: 'melancholy', score: 10 },
        { emotion: 'tension', score: 30 },
        { emotion: 'passion', score: 35 },
        { emotion: 'wonder', score: 55 },
        { emotion: 'sadness', score: 5 },
      ],
      targetAudience: ['Любители сатиры', 'Семейный просмотр', 'Студенты'],
      cast: ['Геннадий Овсянников', 'Александр Подобед'],
      reviews: [
        { id: 'r3', author: 'Елена В.', date: '2025-10-10', rating: 5, text: 'Смеялись от души! Актёры великолепно передали характеры персонажей.', emotions: [{ emotion: 'joy', score: 95 }] },
      ],
    },
    {
      id: '3',
      theaterId: 'gorky',
      title: 'Король Лир',
      genre: 'Трагедия',
      duration: '3ч 10мин',
      director: 'Сергей Ковальчик',
      synopsis: 'Монументальная трагедия Шекспира о старом короле, разделившем королевство между дочерьми. Мощная история о власти, предательстве, любви и безумии в интерпретации Горьковского театра.',
      imageUrl: '/images/performance-3.jpg',
      heroImageUrl: '/images/performance-3-hero.png',
      rating: 4.8,
      reviewCount: 156,
      premiere: '2023',
      emotionProfile: [
        { emotion: 'joy', score: 10 },
        { emotion: 'melancholy', score: 80 },
        { emotion: 'tension', score: 90 },
        { emotion: 'passion', score: 70 },
        { emotion: 'wonder', score: 60 },
        { emotion: 'sadness', score: 85 },
      ],
      targetAudience: ['Ценители Шекспира', 'Опытные театралы', 'Студенты театральных вузов'],
      cast: ['Виктор Манаев', 'Ольга Нефёдова', 'Татьяна Мархель'],
      reviews: [
        { id: 'r4', author: 'Дмитрий С.', date: '2026-01-05', rating: 5, text: 'Невероятная мощь! Главный актёр буквально проживает роль Лира. Один из лучших спектаклей сезона.', emotions: [{ emotion: 'tension', score: 95 }, { emotion: 'sadness', score: 85 }] },
      ],
    },
    {
      id: '4',
      theaterId: 'gorky',
      title: 'Чайка',
      genre: 'Драма',
      duration: '2ч 40мин',
      director: 'Сергей Ковальчик',
      synopsis: 'Чеховская «Чайка» — история о несбывшихся мечтах, неразделённой любви и поиске смысла в искусстве. Тонкая психологическая драма, где каждый персонаж ведёт свою борьбу с жизнью.',
      imageUrl: '/images/performance-4.jpg',
      heroImageUrl: '/images/performance-4-hero.png',
      rating: 4.6,
      reviewCount: 98,
      premiere: '2021',
      emotionProfile: [
        { emotion: 'joy', score: 20 },
        { emotion: 'melancholy', score: 85 },
        { emotion: 'tension', score: 45 },
        { emotion: 'passion', score: 65 },
        { emotion: 'wonder', score: 40 },
        { emotion: 'sadness', score: 75 },
      ],
      targetAudience: ['Любители Чехова', 'Романтики', 'Интеллектуалы'],
      cast: ['Ольга Нефёдова', 'Роман Подоляко', 'Татьяна Мархель'],
      reviews: [
        { id: 'r5', author: 'Ирина М.', date: '2025-09-22', rating: 5, text: 'Чехов в лучшем виде. Каждая реплика — как удар в сердце. Вышла из театра другим человеком.', emotions: [{ emotion: 'melancholy', score: 90 }, { emotion: 'passion', score: 70 }] },
      ],
    },
    {
      id: '5',
      theaterId: 'youth',
      title: 'Мастер и Маргарита',
      genre: 'Трагикомедия',
      duration: '3ч 00мин',
      director: 'Виталий Барковский',
      synopsis: 'Дерзкая интерпретация романа Булгакова. Воланд со свитой врывается в повседневность, обнажая человеческие пороки. Смешение реальности и фантасмагории в авангардной постановке Молодёжного театра.',
      imageUrl: '/images/performance-5.jpg',
      heroImageUrl: '/images/performance-5-hero.png',
      rating: 4.9,
      reviewCount: 201,
      premiere: '2024',
      emotionProfile: [
        { emotion: 'joy', score: 50 },
        { emotion: 'melancholy', score: 55 },
        { emotion: 'tension', score: 80 },
        { emotion: 'passion', score: 90 },
        { emotion: 'wonder', score: 95 },
        { emotion: 'sadness', score: 40 },
      ],
      targetAudience: ['Поклонники Булгакова', 'Любители авангарда', 'Молодёжь', 'Искушённые зрители'],
      cast: ['Дмитрий Есеневич', 'Анна Хитрик', 'Павел Остроух'],
      reviews: [
        { id: 'r6', author: 'Алексей Р.', date: '2026-02-14', rating: 5, text: 'Шедевр! Три часа пролетели как один миг. Воланд — абсолютно гениален.', emotions: [{ emotion: 'wonder', score: 100 }, { emotion: 'passion', score: 85 }] },
        { id: 'r7', author: 'Наталья Д.', date: '2026-01-28', rating: 5, text: 'Лучшая постановка «Мастера» из всех, что я видела. Визуальное и эмоциональное потрясение.', emotions: [{ emotion: 'wonder', score: 95 }, { emotion: 'tension', score: 80 }] },
      ],
    },
    {
      id: '6',
      theaterId: 'rtbd',
      title: 'Вишнёвый сад',
      genre: 'Драма',
      duration: '2ч 20мин',
      director: 'Александр Гарцуев',
      synopsis: 'Пронзительная история о гибели старого мира и рождении нового. Чеховские герои прощаются с прошлым — с садом, с домом, с целой эпохой. Элегантная и тонкая постановка РТБД.',
      imageUrl: '/images/performance-6.jpg',
      heroImageUrl: '/images/performance-6-hero.png',
      rating: 4.4,
      reviewCount: 67,
      premiere: '2022',
      emotionProfile: [
        { emotion: 'joy', score: 25 },
        { emotion: 'melancholy', score: 90 },
        { emotion: 'tension', score: 35 },
        { emotion: 'passion', score: 30 },
        { emotion: 'wonder', score: 45 },
        { emotion: 'sadness', score: 80 },
      ],
      targetAudience: ['Любители Чехова', 'Ценители тонкой драматургии', 'Интроверты'],
      cast: ['Ирина Жук', 'Алексей Шедько'],
      reviews: [
        { id: 'r8', author: 'Ольга К.', date: '2025-11-01', rating: 4, text: 'Красивый и грустный спектакль. Чувствуешь, как время утекает сквозь пальцы.', emotions: [{ emotion: 'melancholy', score: 85 }, { emotion: 'sadness', score: 75 }] },
      ],
    },
    {
      id: '7',
      theaterId: 'oblast',
      title: 'Свадьба',
      genre: 'Комедия',
      duration: '1ч 40мин',
      director: 'Наталья Бурмистрова',
      synopsis: 'Искромётная комедия по мотивам рассказов Чехова. Свадебное торжество превращается в фарс, полный недоразумений, смешных ситуаций и узнаваемых типажей. Лёгкий и весёлый спектакль для прекрасного вечера.',
      imageUrl: '/images/performance-7.jpg',
      heroImageUrl: '/images/performance-7-hero.png',
      rating: 4.2,
      reviewCount: 45,
      premiere: '2020',
      emotionProfile: [
        { emotion: 'joy', score: 90 },
        { emotion: 'melancholy', score: 5 },
        { emotion: 'tension', score: 20 },
        { emotion: 'passion', score: 40 },
        { emotion: 'wonder', score: 50 },
        { emotion: 'sadness', score: 5 },
      ],
      targetAudience: ['Для первого свидания', 'Семейный просмотр', 'Любители Чехова'],
      cast: ['Дмитрий Козловский', 'Анна Сидорова'],
      reviews: [
        { id: 'r9', author: 'Виктор Н.', date: '2025-08-15', rating: 4, text: 'Отличный лёгкий спектакль. Смеялся весь вечер!', emotions: [{ emotion: 'joy', score: 88 }] },
      ],
    },
    {
      id: '8',
      theaterId: 'kino',
      title: 'Гамлет',
      genre: 'Трагедия',
      duration: '2ч 50мин',
      director: 'Алексей Дударев',
      synopsis: 'Камерное и интимное прочтение великой трагедии Шекспира. В небольшом зале Театра-студии Гамлет становится близким и понятным, а его вопрос «быть или не быть» звучит особенно остро и лично.',
      imageUrl: '/images/performance-8.jpg',
      heroImageUrl: '/images/performance-8-hero.png',
      rating: 4.3,
      reviewCount: 34,
      premiere: '2024',
      emotionProfile: [
        { emotion: 'joy', score: 5 },
        { emotion: 'melancholy', score: 70 },
        { emotion: 'tension', score: 85 },
        { emotion: 'passion', score: 60 },
        { emotion: 'wonder', score: 50 },
        { emotion: 'sadness', score: 70 },
      ],
      targetAudience: ['Любители камерного театра', 'Ценители Шекспира', 'Студенты'],
      cast: ['Кирилл Дыцевич', 'Ирина Нарбекова'],
      reviews: [
        { id: 'r10', author: 'Светлана Б.', date: '2025-12-02', rating: 5, text: 'Камерная атмосфера делает этот спектакль невероятно мощным. Гамлет — на расстоянии вытянутой руки.', emotions: [{ emotion: 'tension', score: 90 }, { emotion: 'melancholy', score: 75 }] },
      ],
    },
    {
      id: '9',
      theaterId: 'kupala',
      title: 'Тутэйшыя',
      genre: 'Драма',
      duration: '2ч 15мин',
      director: 'Николай Пинигин',
      synopsis: 'Пьеса Янки Купалы о судьбе белорусского народа в годы Первой мировой войны и революции. Главный герой Микита Зносак мечется между разными политическими силами, не находя себя. Спектакль о национальной идентичности, о том, что значит быть «тутэйшым» — здешним.',
      imageUrl: '/images/performance-9.jpg',
      heroImageUrl: '/images/performance-9.jpg',
      rating: 4.6,
      reviewCount: 112,
      premiere: '2005',
      emotionProfile: [
        { emotion: 'joy', score: 15 },
        { emotion: 'melancholy', score: 75 },
        { emotion: 'tension', score: 65 },
        { emotion: 'passion', score: 55 },
        { emotion: 'wonder', score: 50 },
        { emotion: 'sadness', score: 70 },
      ],
      targetAudience: ['Любители белорусской классики', 'Интеллектуалы', 'Студенты', 'Для иностранных гостей'],
      cast: ['Зоя Белохвостик', 'Александр Подобед', 'Мария Захаревич', 'Геннадий Овсянников'],
      reviews: [
        { id: 'r11', author: 'Павел Г.', date: '2026-01-12', rating: 5, text: 'Пронзительный спектакль о нашей истории. Каждое слово Купалы звучит как никогда актуально.', emotions: [{ emotion: 'melancholy', score: 80 }, { emotion: 'passion', score: 65 }] },
        { id: 'r12', author: 'Тамара С.', date: '2025-12-08', rating: 4, text: 'Глубокий, честный спектакль. Пинигин умеет работать с белорусским материалом.', emotions: [{ emotion: 'tension', score: 60 }, { emotion: 'sadness', score: 70 }] },
      ],
    },
    {
      id: '10',
      theaterId: 'kupala',
      title: 'Раскіданае гняздо',
      genre: 'Трагедия',
      duration: '2ч 45мин',
      director: 'Валерий Анисенко',
      synopsis: 'Трагедия Янки Купалы о разорённой белорусской семье, вынужденной покинуть родную землю. Судьба Зосі, Симона и их близких становится символом трагедии целого народа, лишённого корней.',
      imageUrl: '/images/performance-10.jpg',
      heroImageUrl: '/images/performance-10.jpg',
      rating: 4.5,
      reviewCount: 78,
      premiere: '1999',
      emotionProfile: [
        { emotion: 'joy', score: 10 },
        { emotion: 'melancholy', score: 85 },
        { emotion: 'tension', score: 60 },
        { emotion: 'passion', score: 50 },
        { emotion: 'wonder', score: 35 },
        { emotion: 'sadness', score: 90 },
      ],
      targetAudience: ['Любители белорусской классики', 'Опытные театралы', 'Ценители трагедии'],
      cast: ['Зоя Белохвостик', 'Геннадий Овсянников', 'Александр Подобед'],
      reviews: [
        { id: 'r13', author: 'Нина Л.', date: '2025-10-20', rating: 5, text: 'Плакала весь второй акт. Купала — гений, а постановка достойна его слова.', emotions: [{ emotion: 'sadness', score: 95 }, { emotion: 'melancholy', score: 85 }] },
      ],
    },
    {
      id: '11',
      theaterId: 'gorky',
      title: 'Три сестры',
      genre: 'Драма',
      duration: '3ч 00мин',
      director: 'Сергей Ковальчик',
      synopsis: 'Три сестры мечтают уехать в Москву, но жизнь неумолимо держит их в провинции. Чехов исследует томление по несбыточному, усталость от повседневности и неспособность изменить свою судьбу.',
      imageUrl: '/images/performance-11.jpg',
      heroImageUrl: '/images/performance-11-hero.png',
      rating: 4.7,
      reviewCount: 134,
      premiere: '2022',
      emotionProfile: [
        { emotion: 'joy', score: 15 },
        { emotion: 'melancholy', score: 90 },
        { emotion: 'tension', score: 40 },
        { emotion: 'passion', score: 55 },
        { emotion: 'wonder', score: 35 },
        { emotion: 'sadness', score: 85 },
      ],
      targetAudience: ['Любители Чехова', 'Интеллектуалы', 'Романтики', 'Опытные театралы'],
      cast: ['Ольга Нефёдова', 'Татьяна Мархель', 'Виктор Манаев', 'Роман Подоляко'],
      reviews: [
        { id: 'r14', author: 'Екатерина В.', date: '2026-02-03', rating: 5, text: 'Три часа, которые ощущаются как вечность — в хорошем смысле. Абсолютный Чехов.', emotions: [{ emotion: 'melancholy', score: 92 }, { emotion: 'sadness', score: 80 }] },
        { id: 'r15', author: 'Максим О.', date: '2026-01-17', rating: 4, text: 'Мощная постановка. Ковальчик знает, как работать с Чеховым.', emotions: [{ emotion: 'tension', score: 50 }, { emotion: 'melancholy', score: 85 }] },
      ],
    },
    {
      id: '12',
      theaterId: 'youth',
      title: 'Ревизор',
      genre: 'Комедия',
      duration: '2ч 10мин',
      director: 'Виталий Барковский',
      synopsis: 'Гоголевская комедия в энергичной постановке Молодёжного театра. Хлестаков — не просто ловкий мошенник, а зеркало, в котором чиновничья Россия узнаёт саму себя. Острый, злободневный и невероятно смешной спектакль.',
      imageUrl: '/images/performance-12.jpg',
      heroImageUrl: '/images/performance-12.jpg',
      rating: 4.5,
      reviewCount: 96,
      premiere: '2023',
      emotionProfile: [
        { emotion: 'joy', score: 85 },
        { emotion: 'melancholy', score: 10 },
        { emotion: 'tension', score: 45 },
        { emotion: 'passion', score: 50 },
        { emotion: 'wonder', score: 60 },
        { emotion: 'sadness', score: 5 },
      ],
      targetAudience: ['Любители сатиры', 'Молодёжь', 'Студенты', 'Семейный просмотр'],
      cast: ['Дмитрий Есеневич', 'Павел Остроух', 'Анна Хитрик'],
      reviews: [
        { id: 'r16', author: 'Роман К.', date: '2026-02-20', rating: 5, text: 'Хлестаков — просто бомба! Такой энергии на сцене давно не видел.', emotions: [{ emotion: 'joy', score: 92 }, { emotion: 'wonder', score: 70 }] },
      ],
    },
    {
      id: '13',
      theaterId: 'youth',
      title: 'Поминальная молитва',
      genre: 'Драма',
      duration: '2ч 50мин',
      director: 'Александр Янушкевич',
      synopsis: 'Спектакль по пьесе Григория Горина на основе рассказов Шолом-Алейхема. История молочника Тевье, его семьи и маленькой еврейской общины на переломе эпох. О вере, любви, потере и человеческом достоинстве перед лицом истории.',
      imageUrl: '/images/performance-13.jpg',
      heroImageUrl: '/images/performance-13-hero.png',
      rating: 4.8,
      reviewCount: 167,
      premiere: '2019',
      emotionProfile: [
        { emotion: 'joy', score: 40 },
        { emotion: 'melancholy', score: 80 },
        { emotion: 'tension', score: 55 },
        { emotion: 'passion', score: 75 },
        { emotion: 'wonder', score: 50 },
        { emotion: 'sadness', score: 85 },
      ],
      targetAudience: ['Опытные театралы', 'Интеллектуалы', 'Любители классики', 'Взрослая аудитория'],
      cast: ['Дмитрий Есеневич', 'Анна Хитрик', 'Александр Янушкевич'],
      reviews: [
        { id: 'r17', author: 'Галина П.', date: '2026-03-01', rating: 5, text: 'Один из лучших спектаклей в моей жизни. Смеялась и плакала одновременно.', emotions: [{ emotion: 'sadness', score: 88 }, { emotion: 'joy', score: 55 }] },
        { id: 'r18', author: 'Игорь Т.', date: '2026-02-10', rating: 5, text: 'Тевье — это роль жизни для актёра. Совершенно потрясающе.', emotions: [{ emotion: 'passion', score: 80 }, { emotion: 'melancholy', score: 75 }] },
      ],
    },
    {
      id: '14',
      theaterId: 'youth',
      title: 'Ромео и Джульетта',
      genre: 'Трагедия',
      duration: '2ч 30мин',
      director: 'Александр Янушкевич',
      synopsis: 'Шекспировская трагедия в современном прочтении Молодёжного театра. Верона превращается в любой большой город, где ненависть семей оказывается сильнее любви молодых. Страстный, стремительный, визуально яркий спектакль.',
      imageUrl: '/images/performance-14.jpg',
      heroImageUrl: '/images/performance-14.jpg',
      rating: 4.6,
      reviewCount: 145,
      premiere: '2021',
      emotionProfile: [
        { emotion: 'joy', score: 30 },
        { emotion: 'melancholy', score: 60 },
        { emotion: 'tension', score: 75 },
        { emotion: 'passion', score: 95 },
        { emotion: 'wonder', score: 65 },
        { emotion: 'sadness', score: 80 },
      ],
      targetAudience: ['Молодёжь', 'Романтики', 'Любители Шекспира', 'Для первого свидания'],
      cast: ['Павел Остроух', 'Анна Хитрик', 'Дмитрий Есеневич'],
      reviews: [
        { id: 'r19', author: 'Анастасия К.', date: '2026-01-30', rating: 5, text: 'Невероятно красивый спектакль. Джульетта — просто богиня. Плакала в финале.', emotions: [{ emotion: 'passion', score: 95 }, { emotion: 'sadness', score: 85 }] },
      ],
    },
    {
      id: '15',
      theaterId: 'gorky',
      title: 'На дне',
      genre: 'Драма',
      duration: '2ч 40мин',
      director: 'Сергей Ковальчик',
      synopsis: 'Горьковская пьеса о людях, выброшенных на обочину жизни. Ночлежка становится срезом общества, где каждый сохраняет остатки мечты и достоинства. Философский вопрос о правде и лжи как спасении звучит со сцены Горьковского театра.',
      imageUrl: '/images/performance-15.jpg',
      heroImageUrl: '/images/performance-15.jpg',
      rating: 4.4,
      reviewCount: 88,
      premiere: '2020',
      emotionProfile: [
        { emotion: 'joy', score: 5 },
        { emotion: 'melancholy', score: 85 },
        { emotion: 'tension', score: 60 },
        { emotion: 'passion', score: 45 },
        { emotion: 'wonder', score: 40 },
        { emotion: 'sadness', score: 80 },
      ],
      targetAudience: ['Опытные театралы', 'Любители русской классики', 'Интеллектуалы'],
      cast: ['Виктор Манаев', 'Ольга Нефёдова', 'Роман Подоляко', 'Татьяна Мархель'],
      reviews: [
        { id: 'r20', author: 'Борис Ш.', date: '2025-11-15', rating: 4, text: 'Тяжёлый, но необходимый спектакль. Горький на родной сцене — это особенно символично.', emotions: [{ emotion: 'melancholy', score: 85 }, { emotion: 'tension', score: 60 }] },
      ],
    },
    {
      id: '16',
      theaterId: 'gorky',
      title: 'Отелло',
      genre: 'Трагедия',
      duration: '2ч 55мин',
      director: 'Сергей Ковальчик',
      synopsis: 'Трагедия ревности и манипуляции в постановке Горьковского театра. Яго плетёт сети лжи, а Отелло — самый честный человек на свете — становится его жертвой. Мощная актёрская работа в одном из главных шекспировских сюжетов.',
      imageUrl: '/images/performance-16.jpg',
      heroImageUrl: '/images/performance-16-hero.png',
      rating: 4.5,
      reviewCount: 102,
      premiere: '2023',
      emotionProfile: [
        { emotion: 'joy', score: 5 },
        { emotion: 'melancholy', score: 65 },
        { emotion: 'tension', score: 95 },
        { emotion: 'passion', score: 85 },
        { emotion: 'wonder', score: 45 },
        { emotion: 'sadness', score: 75 },
      ],
      targetAudience: ['Ценители Шекспира', 'Опытные театралы', 'Любители психологической драмы'],
      cast: ['Виктор Манаев', 'Роман Подоляко', 'Ольга Нефёдова'],
      reviews: [
        { id: 'r21', author: 'Владимир К.', date: '2026-02-25', rating: 5, text: 'Яго в этом спектакле — настоящее исчадие ада. Актёр держит в напряжении весь зал.', emotions: [{ emotion: 'tension', score: 98 }, { emotion: 'passion', score: 80 }] },
        { id: 'r22', author: 'Людмила В.', date: '2026-01-10', rating: 4, text: 'Сильная постановка. Финальная сцена — просто разрывает сердце.', emotions: [{ emotion: 'sadness', score: 85 }, { emotion: 'tension', score: 90 }] },
      ],
    },
    {
      id: '17',
      theaterId: 'rtbd',
      title: 'Дядя Ваня',
      genre: 'Драма',
      duration: '2ч 30мин',
      director: 'Александр Гарцуев',
      synopsis: 'Чехов о людях, которые осознали, что жизнь прошла впустую. Дядя Ваня и Соня тянут лямку в поместье, пока профессор Серебряков пожинает плоды чужого труда. Спектакль РТБД — тихий, пронзительный, без лишних слов.',
      imageUrl: '/images/performance-17.jpg',
      heroImageUrl: '/images/performance-17.jpg',
      rating: 4.5,
      reviewCount: 74,
      premiere: '2021',
      emotionProfile: [
        { emotion: 'joy', score: 10 },
        { emotion: 'melancholy', score: 92 },
        { emotion: 'tension', score: 50 },
        { emotion: 'passion', score: 40 },
        { emotion: 'wonder', score: 30 },
        { emotion: 'sadness', score: 88 },
      ],
      targetAudience: ['Любители Чехова', 'Ценители тонкой драматургии', 'Интроверты', 'Опытные театралы'],
      cast: ['Ирина Жук', 'Алексей Шедько', 'Сергей Журавель'],
      reviews: [
        { id: 'r23', author: 'Марина Ф.', date: '2025-12-20', rating: 5, text: 'После спектакля долго не могла говорить. «Надо жить» — это звучит как откровение.', emotions: [{ emotion: 'melancholy', score: 90 }, { emotion: 'sadness', score: 88 }] },
      ],
    },
    {
      id: '18',
      theaterId: 'rtbd',
      title: 'Страсти по Авдею',
      genre: 'Трагикомедия',
      duration: '2ч 00мин',
      director: 'Александр Гарцуев',
      synopsis: 'Пьеса Алексея Дударева о белорусской деревне и непростых судьбах её жителей. Авдей — человек не от мира сего, живущий по собственным законам чести. История о столкновении чистой души с жестокой реальностью.',
      imageUrl: '/images/performance-18.jpg',
      heroImageUrl: '/images/performance-18.jpg',
      rating: 4.3,
      reviewCount: 56,
      premiere: '2018',
      emotionProfile: [
        { emotion: 'joy', score: 35 },
        { emotion: 'melancholy', score: 70 },
        { emotion: 'tension', score: 55 },
        { emotion: 'passion', score: 60 },
        { emotion: 'wonder', score: 45 },
        { emotion: 'sadness', score: 65 },
      ],
      targetAudience: ['Любители белорусской драматургии', 'Ценители народных историй', 'Взрослая аудитория'],
      cast: ['Алексей Шедько', 'Ирина Жук', 'Сергей Журавель'],
      reviews: [
        { id: 'r24', author: 'Степан Р.', date: '2025-09-14', rating: 4, text: 'Дударев умеет писать про наших людей. Авдей — это про каждого из нас немного.', emotions: [{ emotion: 'melancholy', score: 72 }, { emotion: 'passion', score: 58 }] },
      ],
    },
    {
      id: '19',
      theaterId: 'kino',
      title: 'Женитьба',
      genre: 'Комедия',
      duration: '1ч 55мин',
      director: 'Алексей Лелявский',
      synopsis: 'Гоголевская комедия об ужасах сватовства в камерном исполнении Театра-студии. Подколёсин бежит от собственного счастья, а вся эта история превращается в абсурдный и невероятно смешной карнавал человеческих слабостей.',
      imageUrl: '/images/performance-19.jpg',
      heroImageUrl: '/images/performance-19-hero.png',
      rating: 4.4,
      reviewCount: 49,
      premiere: '2022',
      emotionProfile: [
        { emotion: 'joy', score: 88 },
        { emotion: 'melancholy', score: 10 },
        { emotion: 'tension', score: 30 },
        { emotion: 'passion', score: 35 },
        { emotion: 'wonder', score: 55 },
        { emotion: 'sadness', score: 5 },
      ],
      targetAudience: ['Любители Гоголя', 'Семейный просмотр', 'Первый поход в театр', 'Любители камерного театра'],
      cast: ['Кирилл Дыцевич', 'Ирина Нарбекова', 'Александр Беспалый'],
      reviews: [
        { id: 'r25', author: 'Сергей М.', date: '2025-10-30', rating: 4, text: 'Лёгкий, смешной, атмосферный. Маленький зал создаёт особую близость с актёрами.', emotions: [{ emotion: 'joy', score: 88 }, { emotion: 'wonder', score: 50 }] },
      ],
    },
    {
      id: '20',
      theaterId: 'oblast',
      title: 'Иванов',
      genre: 'Драма',
      duration: '2ч 20мин',
      director: 'Наталья Бурмистрова',
      synopsis: 'Редко ставящаяся пьеса Чехова об усталом человеке, который разочаровался в жизни и в себе. Иванов — не злодей и не герой, а просто человек, которому стало невыносимо тяжело жить. Тонкий и горький спектакль Областного театра.',
      imageUrl: '/images/performance-20.jpg',
      heroImageUrl: '/images/performance-20.jpg',
      rating: 4.2,
      reviewCount: 38,
      premiere: '2023',
      emotionProfile: [
        { emotion: 'joy', score: 5 },
        { emotion: 'melancholy', score: 88 },
        { emotion: 'tension', score: 45 },
        { emotion: 'passion', score: 30 },
        { emotion: 'wonder', score: 25 },
        { emotion: 'sadness', score: 82 },
      ],
      targetAudience: ['Ценители Чехова', 'Опытные театралы', 'Интроверты'],
      cast: ['Дмитрий Козловский', 'Анна Сидорова', 'Евгений Лойко'],
      reviews: [
        { id: 'r26', author: 'Лариса Н.', date: '2025-11-22', rating: 4, text: 'Пьесу редко ставят — и зря. Областной театр сделал честную и глубокую работу.', emotions: [{ emotion: 'melancholy', score: 88 }, { emotion: 'sadness', score: 80 }] },
      ],
    },
  ];

  for (const p of performances) {
    const { emotionProfile, targetAudience, cast, reviews, ...perfData } = p;

    await prisma.performance.upsert({
      where: { id: perfData.id },
      update: { heroImageUrl: perfData.heroImageUrl ?? null },
      create: {
        ...perfData,
        emotionProfile: { create: emotionProfile },
        targetAudience: { create: targetAudience.map((tag) => ({ tag })) },
        cast: { create: cast.map((name) => ({ name })) },
        reviews: {
          create: reviews.map(({ emotions, ...r }) => ({
            ...r,
            emotions: { create: emotions },
          })),
        },
      },
    });
  }

  console.log('Seed completed: 6 theaters, 20 performances');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
